package com.shop.webshop.dom;

// default package
// Generated Nov 7, 2018 3:51:58 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "ORDERS", schema = "APP")
public class Orders implements java.io.Serializable {

	private int oid;
	private int uid;

	public Orders() {
	}

	public Orders(int oid, int uid) {
		this.oid = oid;
		this.uid = uid;
	}

	@Id

	@Column(name = "OID", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "UID", nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

}
