package com.shop.webshop.dom;

// default package
// Generated Nov 7, 2018 3:51:58 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orderitems generated by hbm2java
 */
@Entity
@Table(name = "ORDERITEMS", schema = "APP")
public class Orderitems implements java.io.Serializable {

	private int iid;
	private int oid;
	private int pid;
	private int pamount;

	public Orderitems() {
	}

	public Orderitems(int iid, int oid, int pid, int pamount) {
		this.iid = iid;
		this.oid = oid;
		this.pid = pid;
		this.pamount = pamount;
	}

	@Id
	@Column(name = "IID", unique = true, nullable = false)
	public int getIid() {
		return this.iid;
	}

	public void setIid(int iid) {
		this.iid = iid;
	}

	@Column(name = "OID", nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "PID", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "PAMOUNT", nullable = false)
	public int getPamount() {
		return this.pamount;
	}

	public void setPamount(int pamount) {
		this.pamount = pamount;
	}

}
