package com.shop.webshop.dom;

// default package
// Generated Nov 7, 2018 3:51:58 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTS", schema = "APP")
public class Products implements java.io.Serializable {

	private int pid;
	private String pname;
	private Double pprice;
	private Integer pweight;
	private String pdescription;

	public Products() {
	}

	public Products(int pid, String pname) {
		this.pid = pid;
		this.pname = pname;
	}

	public Products(int pid, String pname, Double pprice, Integer pweight, String pdescription) {
		this.pid = pid;
		this.pname = pname;
		this.pprice = pprice;
		this.pweight = pweight;
		this.pdescription = pdescription;
	}

	@Id

	@Column(name = "PID", unique = true, nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "PNAME", nullable = false, length = 60)
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "PPRICE", precision = 52, scale = 0)
	public Double getPprice() {
		return this.pprice;
	}

	public void setPprice(Double pprice) {
		this.pprice = pprice;
	}

	@Column(name = "PWEIGHT")
	public Integer getPweight() {
		return this.pweight;
	}

	public void setPweight(Integer pweight) {
		this.pweight = pweight;
	}

	@Column(name = "PDESCRIPTION", length = 500)
	public String getPdescription() {
		return this.pdescription;
	}

	public void setPdescription(String pdescription) {
		this.pdescription = pdescription;
	}

}
