package com.shop.webshop.dom;

// default package
// Generated Nov 7, 2018 3:51:58 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "STOCK", schema = "APP")
public class Stock implements java.io.Serializable {

	private int sid;
	private int pid;
	private int pamount;
	private Double pshippingprice;
	private Integer pshippingtime;

	public Stock() {
	}

	public Stock(int sid, int pid, int pamount) {
		this.sid = sid;
		this.pid = pid;
		this.pamount = pamount;
	}

	public Stock(int sid, int pid, int pamount, Double pshippingprice, Integer pshippingtime) {
		this.sid = sid;
		this.pid = pid;
		this.pamount = pamount;
		this.pshippingprice = pshippingprice;
		this.pshippingtime = pshippingtime;
	}

	@Id

	@Column(name = "SID", unique = true, nullable = false)
	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	@Column(name = "PID", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "PAMOUNT", nullable = false)
	public int getPamount() {
		return this.pamount;
	}

	public void setPamount(int pamount) {
		this.pamount = pamount;
	}

	@Column(name = "PSHIPPINGPRICE", precision = 52, scale = 0)
	public Double getPshippingprice() {
		return this.pshippingprice;
	}

	public void setPshippingprice(Double pshippingprice) {
		this.pshippingprice = pshippingprice;
	}

	@Column(name = "PSHIPPINGTIME")
	public Integer getPshippingtime() {
		return this.pshippingtime;
	}

	public void setPshippingtime(Integer pshippingtime) {
		this.pshippingtime = pshippingtime;
	}

}
