package com.shop.webshop.dom;

// default package
// Generated Nov 7, 2018 3:51:58 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS", schema = "APP")
public class Users implements java.io.Serializable {

	private int uid;
	private String username;
	private String ufirstname;
	private String ulastname;
	private String upassword;

	public Users() {
	}

	public Users(int uid) {
		this.uid = uid;
	}

	public Users(int uid, String username, String ufirstname, String ulastname, String upassword) {
		this.uid = uid;
		this.username = username;
		this.ufirstname = ufirstname;
		this.ulastname = ulastname;
		this.upassword = upassword;
	}

	@Id

	@Column(name = "UID", unique = true, nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "USERNAME", length = 60)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "UFIRSTNAME", length = 60)
	public String getUfirstname() {
		return this.ufirstname;
	}

	public void setUfirstname(String ufirstname) {
		this.ufirstname = ufirstname;
	}

	@Column(name = "ULASTNAME", length = 60)
	public String getUlastname() {
		return this.ulastname;
	}

	public void setUlastname(String ulastname) {
		this.ulastname = ulastname;
	}

	@Column(name = "UPASSWORD", length = 60)
	public String getUpassword() {
		return this.upassword;
	}

	public void setUpassword(String upassword) {
		this.upassword = upassword;
	}

}
